name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        redis:
          - image: redis:7.4.1-alpine
            coverage: true
          - image: redis:8.0-M02-alpine
            coverage: false

    runs-on: ubuntu-latest
    container: node:22-alpine
    services:
      redis:
        image: ${{ matrix.redis.image }}
    steps:
      - uses: actions/checkout@v4

      - run: yarn install --frozen-lockfile

      - run: yarn compile

      - run: echo "COVERAGE=${{ matrix.redis.coverage }}" >> "$GITHUB_ENV"

      - if: env.COVERAGE == 'true'
        run: yarn test:coverage
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - if: env.COVERAGE != 'true'
        run: yarn test:all
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - if: env.COVERAGE == 'true'
        run: apk add git curl gnupg coreutils

      - if: env.COVERAGE == 'true'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: ./coverage/lcov.info
          os: alpine
          token: ${{ secrets.CODECOV_TOKEN }}
